### ISSUE TITLE
ClassNotFoundException when attempting to load LagAssist on Paper/Spigot server

### ISSUE THREAD

**Issue by OtakuSweett** [alvindimas05/LagAssist#2]
### Description:
When I start my Minecraft server using UniverseSpigot 1.21.1-DEV (a fork of Paper/Spigot 1.21.1), the `LagAssist` plugin (version 2.31-1.21.1) loads correctly, but it generates multiple `ClassNotFoundException` warnings. While the plugin appears to function, these errors might cause undetected issues in the future. The issue specifically occurs in an environment using UniverseSpigot 1.21.1-DEV.

### Steps to Reproduce:
1. Download and install UniverseSpigot version 1.21.1-DEV (a fork of Paper/Spigot).
2. Add `LagAssist` version 2.31-1.21.1 to the `plugins` folder.
3. Start the server using `java -jar paper.jar`.
4. Observe the server logs for warnings.

### Expected Behavior:
I expected `LagAssist` to load without generating class errors and to function correctly without any warnings.

### Actual Behavior:
The server throws multiple `ClassNotFoundException` warnings, indicating that it couldn't find the classes `org.bukkit.craftbukkit.craftbukkit.CraftWorld`, `CraftBlock`, and `CraftPlayer`, among others. Although the plugin loads, these errors could potentially affect the plugin's functionality or cause performance issues on the server.

### Error Messages:
```plaintext
[02:39:00] [Server thread/WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.CraftWorld
[02:39:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199)
[02:39:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166)
[02:39:00] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[02:39:00] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[02:39:00] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:534)
[02:39:00] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:513)
[02:39:00] [Server thread/WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[02:39:00] [Server thread/WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[02:39:00] [Server thread/WARN]: 	at lagassist-2.31-1.21.1.jar//org.alvindimas05.lagassist.packets.Reflection.getClass(Reflection.java:189)
...
```

### Additional Information:
- **UniverseSpigot Version:** 1.21.1-DEV (a fork of Paper/Spigot)
- **LagAssist Version:** 2.31-1.21.1
- **Other Plugins Installed:** Vault, ViaBackwards, ViaVersion
- **Full Log:** https://mclo.gs/gLq5wIp

**Comment by alvindimas05** [comment]
Fixed on b6a1084 and tested on Purpur 1.21.1. You can try the latest build now.
